FROM nginx:latest

COPY ./index.html /usr/share/nginx/html/index.html
COPY ./index2.html /usr/share/nginx/html/index2.html
COPY ./default.conf /etc/nginx/conf.d/default.conf

# RUN apt-get update
# RUN apt-get install -y vim
