@api_host = http://localhost:8092

### root
GET {{api_host}}

###-------------------- パスパラメータ
GET {{api_host}}/items/999

###
GET {{api_host}}/models/resnet


###-------------------- クエリーパラメータ
GET {{api_host}}/items?skip=1&limit=3

###
GET {{api_host}}/items_q_options/abc?q=xyz
###
GET {{api_host}}/items_q_options/abc


###-------------------- リクエストボディ
POST {{api_host}}/items/
content-type: application/json

{
    "name": "Foo",
    "description": "An optional description",
    "price": 45.2,
    "tax": 3.5
}

###
POST {{api_host}}/items/abc?q=xyz
content-type: application/json

{
    "name": "Foo",
    "description": "An optional description",
    "price": 45.2,
    "tax": 3.5
}


