### List all messages
GET http://localhost:3000/messages


### Create a new message
POST http://localhost:3000/messages
content-type: application/json

{
  "content": "hello"
}


### Get a particular message
GET http://localhost:3000/messages/123123123

### GET APIは存在しない
GET http://localhost:3000/messages_999